--- 
whitelist_rules:
  - trailing_whitespace
  - colon
  - comma
  - vertical_whitespace
  - redundant_string_enum_value
  - implicit_getter
  - line_length
  - opening_brace
  - unused_closure_parameter
  - switch_case_alignment
  - identifier_name
  - operator_whitespace
  - closure_parameter_position
  - unused_optional_binding
# disabled_rules: # rule identifiers to exclude from running
#   - trailing_whitespace
included: # paths to include during linting. `--path` is ignored if present.
  - ../BlockV/Classes
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

identifier_name:
  excluded: # excluded via string array
    - id