--- 
disabled_rules: # rule identifiers to exclude from running
  - multiple_closures_with_trailing_closure # TODO: Remove
  - function_parameter_count # TODO: Remove
  - force_try # TODO: Remove
  - todo

included: # paths to include during linting. `--path` is ignored if present.
  - ../BlockV/Core
  - ../BlockV/Face
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

identifier_name:
  excluded: # excluded via string array
    - id
nesting:
  type_level:
    warning: 2
