--- 
whitelist_rules:
  - colon
  - vertical_whitespace
  - redundant_string_enum_value
  - implicit_getter
  - line_length
  - opening_brace
  - unused_closure_parameter
# disabled_rules: # rule identifiers to exclude from running
#   - trailing_whitespace
included: # paths to include during linting. `--path` is ignored if present.
  - ../BlockV/Classes
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods