use_frameworks!
platform :ios, '10.0'

target 'BlockV_Example' do
    
  pod 'BLOCKv', :path => '../'
  # Uncomment the next line to include the 3D Face.
  #pod 'VatomFace3D'

  target 'BLOCKv_Unit_Tests' do
    inherit! :search_paths
    
  end
end
