use_frameworks!
platform :ios, '11.0'

target 'BlockV_Example' do
    
  pod 'BLOCKv', :path => '../'
  pod 'VatomFace3D', :path => '../../../faces/3D-Face'

  target 'BLOCKv_Unit_Tests' do
    inherit! :search_paths
    
  end
end
